// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbcz7NN2lq4RRJ29ie6L8iBayKa5662Eo',
    appId: '1:1049842791027:web:dce2ad3150a297cf8e3006',
    messagingSenderId: '1049842791027',
    projectId: 'fruitsapp-84abe',
    authDomain: 'fruitsapp-84abe.firebaseapp.com',
    storageBucket: 'fruitsapp-84abe.firebasestorage.app',
    measurementId: 'G-Q4EC3EHJVD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzK5MPWkeCLOk-N1XSfKCpgt2yBxg8OgE',
    appId: '1:1049842791027:android:5fc89490578ff1a88e3006',
    messagingSenderId: '1049842791027',
    projectId: 'fruitsapp-84abe',
    storageBucket: 'fruitsapp-84abe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRDw9501EsUIZkGv8ubETdhs3_DmA0aPM',
    appId: '1:1049842791027:ios:fe5d2fd6d79851af8e3006',
    messagingSenderId: '1049842791027',
    projectId: 'fruitsapp-84abe',
    storageBucket: 'fruitsapp-84abe.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCourse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRDw9501EsUIZkGv8ubETdhs3_DmA0aPM',
    appId: '1:1049842791027:ios:fe5d2fd6d79851af8e3006',
    messagingSenderId: '1049842791027',
    projectId: 'fruitsapp-84abe',
    storageBucket: 'fruitsapp-84abe.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCourse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbcz7NN2lq4RRJ29ie6L8iBayKa5662Eo',
    appId: '1:1049842791027:web:dc8c61617e95bbcd8e3006',
    messagingSenderId: '1049842791027',
    projectId: 'fruitsapp-84abe',
    authDomain: 'fruitsapp-84abe.firebaseapp.com',
    storageBucket: 'fruitsapp-84abe.firebasestorage.app',
    measurementId: 'G-XDTG93NJSE',
  );
}
